/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista06;

/**
 *
 * @author digital
 */
public class Clubes extends javax.swing.JFrame {
    Clube clube1 = new Clube();
    Clube clube2 = new Clube();
    /**
     * Creates new form Clubes
     */
    public Clubes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnVitorias2 = new javax.swing.JButton();
        btnEmpates2 = new javax.swing.JButton();
        lblFrase2 = new javax.swing.JLabel();
        btnDerrotas2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVitorias = new javax.swing.JButton();
        btnEmpates = new javax.swing.JButton();
        btnDerrotas = new javax.swing.JButton();
        lblFrase = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVitorias3 = new javax.swing.JButton();
        btnEmpates3 = new javax.swing.JButton();
        lblFrase3 = new javax.swing.JLabel();
        btnDerrotas3 = new javax.swing.JButton();

        jLabel3.setText("Time 1");

        btnVitorias2.setText("Registrar vitórias");
        btnVitorias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitorias2ActionPerformed(evt);
            }
        });

        btnEmpates2.setText("Registrar empate");
        btnEmpates2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpates2ActionPerformed(evt);
            }
        });

        lblFrase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase2.setText("Vitórias: 0 - Derrotas: 0 - Empates: 0  - Pontos: 0");

        btnDerrotas2.setText("Registrar derrota");
        btnDerrotas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotas2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Time 1");

        btnVitorias.setText("Registrar vitórias");
        btnVitorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoriasActionPerformed(evt);
            }
        });

        btnEmpates.setText("Registrar empate");
        btnEmpates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpatesActionPerformed(evt);
            }
        });

        btnDerrotas.setText("Registrar derrota");
        btnDerrotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotasActionPerformed(evt);
            }
        });

        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Vitórias: 0 - Derrotas: 0 - Empates: 0  - Pontos: 0");

        jLabel4.setText("Time 1");

        btnVitorias3.setText("Registrar vitórias");
        btnVitorias3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitorias3ActionPerformed(evt);
            }
        });

        btnEmpates3.setText("Registrar empate");
        btnEmpates3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpates3ActionPerformed(evt);
            }
        });

        lblFrase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase3.setText("Vitórias: 0 - Derrotas: 0 - Empates: 0  - Pontos: 0");

        btnDerrotas3.setText("Registrar derrota");
        btnDerrotas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotas3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnVitorias)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEmpates)
                                .addGap(81, 81, 81)
                                .addComponent(btnDerrotas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFrase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnVitorias3)
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEmpates3)
                                        .addGap(81, 81, 81)
                                        .addComponent(btnDerrotas3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel4)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitorias)
                    .addComponent(btnEmpates)
                    .addComponent(btnDerrotas))
                .addGap(18, 18, 18)
                .addComponent(lblFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitorias3)
                    .addComponent(btnEmpates3)
                    .addComponent(btnDerrotas3))
                .addGap(18, 18, 18)
                .addComponent(lblFrase3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoriasActionPerformed
        clube1.vitoria();
        clube1.frase();

        lblFrase.setText(clube1.texto);
    }//GEN-LAST:event_btnVitoriasActionPerformed

    private void btnEmpatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpatesActionPerformed
        clube1.empate();
        clube1.frase();

        lblFrase.setText(clube1.texto);
    }//GEN-LAST:event_btnEmpatesActionPerformed

    private void btnDerrotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotasActionPerformed
        clube1.derrota();
        clube1.frase();

        lblFrase.setText(clube1.texto);
    }//GEN-LAST:event_btnDerrotasActionPerformed

    private void btnVitorias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitorias2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVitorias2ActionPerformed

    private void btnEmpates2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpates2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpates2ActionPerformed

    private void btnDerrotas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerrotas2ActionPerformed

    private void btnVitorias3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitorias3ActionPerformed
         clube2.vitoria();
        clube2.frase();

        lblFrase3.setText(clube2.texto);
    }//GEN-LAST:event_btnVitorias3ActionPerformed

    private void btnEmpates3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpates3ActionPerformed
        clube2.empate();
        clube2.frase();

        lblFrase3.setText(clube2.texto);
    }//GEN-LAST:event_btnEmpates3ActionPerformed

    private void btnDerrotas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotas3ActionPerformed
        clube2.derrota();
        clube2.frase();

        lblFrase3.setText(clube2.texto);
        
    }//GEN-LAST:event_btnDerrotas3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clubes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerrotas;
    private javax.swing.JButton btnDerrotas2;
    private javax.swing.JButton btnDerrotas3;
    private javax.swing.JButton btnEmpates;
    private javax.swing.JButton btnEmpates2;
    private javax.swing.JButton btnEmpates3;
    private javax.swing.JButton btnVitorias;
    private javax.swing.JButton btnVitorias2;
    private javax.swing.JButton btnVitorias3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblFrase2;
    private javax.swing.JLabel lblFrase3;
    // End of variables declaration//GEN-END:variables
}
