/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.encapsulamento;
    
/**
 *
 * @author digital
 */
public class Elevadores extends javax.swing.JFrame {
    Elevador elevador1 = new Elevador();
    Elevador elevador2 = new Elevador();
    
    /**
     * Creates new form Elevadores
     */
    public Elevadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHomen = new javax.swing.JButton();
        btnMulher = new javax.swing.JButton();
        btnCrianca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPassageiro = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHomen1 = new javax.swing.JButton();
        btnMulher1 = new javax.swing.JButton();
        btnCrianca1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHomen.setText("Entrar homen");
        btnHomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomenActionPerformed(evt);
            }
        });

        btnMulher.setText("Entrar mulher");
        btnMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherActionPerformed(evt);
            }
        });

        btnCrianca.setText("Entrar criança");
        btnCrianca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriancaActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de passageiros no elevador: ");

        jLabel2.setText("Peso total no elevador: ");

        lblPassageiro.setText("0");

        lblPeso.setText("0");

        jLabel5.setText("kg");

        btnHomen1.setText("Entrar homen");
        btnHomen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomen1ActionPerformed(evt);
            }
        });

        btnMulher1.setText("Entrar mulher");
        btnMulher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulher1ActionPerformed(evt);
            }
        });

        btnCrianca1.setText("Entrar criança");
        btnCrianca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrianca1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total de passageiros no elevador: ");

        jLabel7.setText("Peso total no elevador: ");

        jLabel8.setText("0");

        jLabel9.setText("0");

        jLabel10.setText("kg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnMulher)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrianca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMulher1)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrianca1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomen)
                    .addComponent(btnMulher)
                    .addComponent(btnCrianca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassageiro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPeso)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomen1)
                    .addComponent(btnMulher1)
                    .addComponent(btnCrianca1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomenActionPerformed
        elevador1.entrarHomen();
        
        lblPassageiro.setText((elevador1.cont).toString());
        lblPeso.setText((elevador1.peso).toString());
    }//GEN-LAST:event_btnHomenActionPerformed

    private void btnHomen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomen1ActionPerformed
        elevador2.entrarHomen();
        
        lblPassageiro.setText((elevador2.cont).toString());
        lblPeso.setText((elevador2.peso).toString());
    }//GEN-LAST:event_btnHomen1ActionPerformed

    private void btnMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherActionPerformed
        elevador1.entrarMulher();
        
        lblPassageiro.setText((elevador1.cont).toString());
        lblPeso.setText((elevador1.peso).toString());
    }//GEN-LAST:event_btnMulherActionPerformed

    private void btnCriancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriancaActionPerformed
        elevador1.entrarCrianca();
        
        lblPassageiro.setText((elevador1.cont).toString());
        lblPeso.setText((elevador1.peso).toString());
    }//GEN-LAST:event_btnCriancaActionPerformed

    private void btnMulher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulher1ActionPerformed
        elevador2.entrarMulher();
        
        lblPassageiro.setText((elevador2.cont).toString());
        lblPeso.setText((elevador2.peso).toString());
    }//GEN-LAST:event_btnMulher1ActionPerformed

    private void btnCrianca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrianca1ActionPerformed
        elevador2.entrarCrianca();
        
        lblPassageiro.setText((elevador2.cont).toString());
        lblPeso.setText((elevador2.peso).toString());
    }//GEN-LAST:event_btnCrianca1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elevadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrianca;
    private javax.swing.JButton btnCrianca1;
    private javax.swing.JButton btnHomen;
    private javax.swing.JButton btnHomen1;
    private javax.swing.JButton btnMulher;
    private javax.swing.JButton btnMulher1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPassageiro;
    private javax.swing.JLabel lblPeso;
    // End of variables declaration//GEN-END:variables
}
